### ISSUE TITLE
snakemake.utils not found for cookiecutter profile

### ISSUE THREAD

**Issue by Laura-RC** [beardymcjohnface/Koverage#19]
Koverage fails when using snakemake cookiecutter for slurm. 
Slurm submit script is trying to import snakemake.utils.

Hectatomb example slurm script works fine.

**Comment by beardymcjohnface** [comment]
Laura, I tried to replicate what we did with your account on mine but it seems to be working. The cookiecutter profile might have been updated in that time. Can you try and remake the cookiecutter profile? We can work through it next week if you want.

**Comment by beardymcjohnface** [comment]
Current cookiecutter version seems to be working fine.
