### ISSUE TITLE
Koverage hangs when using complete genome

### ISSUE THREAD

**Issue by biobrad** [beardymcjohnface/Koverage#20]
**Describe the bug**

I have tried running koverage with the following complete genomes:
k279a: https://www.ncbi.nlm.nih.gov/datasets/genome/GCF_000072485.1/
r551-3: https://www.ncbi.nlm.nih.gov/datasets/genome/GCF_000020665.1/

it appears to get stuck at an 'Activating conda environment' stage:

**To Reproduce**

use either of the above genomes as a reference

**Expected behavior**

To not hang. :)

**Screenshots or log files**
Log files should appear in `koverage.out/logs` by default.
The master log file should appear in `koverage.out/koverage.log` by default.
If you are using a Snakemake template, scheduler logs may be created separately and may contain useful information. The logs' location will be specified in the Snakemake profile.

**System (please complete the following information):**
 - OS: [e.g. Ubuntu 22]
 - Program version: [e.g. 1.0.0]

Ubuntu
koverage, version 0.1.3

**Additional context**

I tried cranking the memory up to the max my  machine has but it still seemed to hang.
Relevant logs attached.

[after the ctrl-c.txt](https://github.com/beardymcjohnface/Koverage/files/12138161/after.the.ctrl-c.txt)
[koverage_log.txt](https://github.com/beardymcjohnface/Koverage/files/12138182/koverage_log.txt)

**Comment by biobrad** [comment]
For context, the fastqs i am trying to get the coverage for are short read pairs for Stenotrophomonas isolates

**Comment by beardymcjohnface** [comment]
This is odd. Are you able to manually activate that environment?
```shell
conda activate /home/harbj019/mambaforge/envs/koverage/lib/python3.11/site-packages/koverage/workflow/conda/25dbe6007dd88841289e8e1753ee37b0_
minimap2 -h
```

**Comment by biobrad** [comment]
i think you may have found the issue. :-)
(/home/harbj019/mambaforge/envs/koverage/lib/python3.11/site-packages/koverage/workflow/conda/25dbe6007dd88841289e8e1753ee37b0_)
harbj019@ssventer ~/genomeresults
$ minimap -h
Command 'minimap' not found, but can be installed with:
sudo apt install minimap

**Comment by beardymcjohnface** [comment]
This is still kindof odd. I can only guess that there is something wrong with the environment. Can you try deleting it and rerunning please?
`rm -r /home/harbj019/mambaforge/envs/koverage/lib/python3.11/site-packages/koverage/workflow/conda/25dbe6007dd88841289e8e1753ee37b0_`

**Comment by biobrad** [comment]
One step ahead of you mate. :-)
i have removed the entire koverage env:
conda remove -n koverage --all
then to make sure i did the job properly i threw in a bit of
conda clean --all

Will install koverage into the env and report back with results after running it.

**Comment by biobrad** [comment]
Koverage still be hanging :-( 
When I reinstalled Koverage and tried to run it, it failed at first due to no snakemake, so I installed snakemake into the env. Then it ran, and hung again. 
I tried again with a multi-contig fasta, no problems.

If you are unable to replicate, it could be my python eco system on my ubuntu install. 
I almost borked my whole OS  with a pip install 6 months ago that unfortunately used my local pip and not the pip in the conda environment. By the time i realised what was happening my local python files were a complete mess and I was able to step it back to some level of functionality.

I really need to do a clean install... but as I am sure you are aware... massive pain, especially with Linux... so I am waiting until i have the correct level of motivation.

I have attached the entire Koverage.out in case it is useful to you.

[koverageout.tar.gz](https://github.com/beardymcjohnface/Koverage/files/12170933/koverageout.tar.gz)

**Comment by beardymcjohnface** [comment]
you shouldn't have to manually install snakemake. if you're setting up a conda env for it you only need conda to install python 3.8 or higher, then install koverage with pip. something like:
```shell
conda create -n koverage python=3.10
conda activate koverage 
pip install koverage
```

**Comment by biobrad** [comment]
I didn't think that was right and assumed it would install snake make into
the env. Like I said, I think my python envs are borked as I think I have
snake make installed in my local python and for some reason conda is
thinking the snake make install is satisfied by existence of the local
install (which it shouldn't be looking at anyway)

**Comment by beardymcjohnface** [comment]
Hey Brad, did we ever work out if the python envs were the problem?

**Comment by biobrad** [comment]
Hey mate, I have sent a reply to your work email with further details.
I have tried a few more different ways with venv etc... still being weird. still not convinced my local python envs are not interfering in some way.

**Comment by beardymcjohnface** [comment]
Hi Brad, can you pull the latest version 0.1.4 and tell me if it's now fixed for you?

**Comment by biobrad** [comment]
Will do and will let you know.

**Comment by biobrad** [comment]
It works!!! Thank you sir!
(It also doesn't break the report, which is nice. :-))
